name: Deploy to Amazon ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1 #not used, but can be used as ${{env.AWS_REGION}}

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{secrets.AWS_REGION}}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag and push image to Amazon ECR
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws ecr-public get-login-password --region ${{secrets.AWS_REGION}} | docker login --username AWS --password-stdin ${{secrets.ECR_REGISTRY}}
          docker build -t ${{secrets.ECR_REPOSITORY}}:$IMAGE_TAG .
          docker tag ${{secrets.ECR_REPOSITORY}}:$IMAGE_TAG ${{secrets.ECR_REGISTRY}}/${{secrets.ECR_REPOSITORY}}:$IMAGE_TAG
          docker push ${{secrets.ECR_REGISTRY}}/${{secrets.ECR_REPOSITORY}}:$IMAGE_TAG
