name: Deploy to AMAZON EKS

on:
  push:
    branches:
      - main

env:
  EKS_CLUSTER: ridiculous-wardrobe-1659257681

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout
        id: checkout-branch
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        id: aws-config
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Dockerhub
        id: docker-login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PWD }}
      - name: Build, tag and push image to Dockerhub
        id: build-image
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:$IMAGE_TAG .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:$IMAGE_TAG
          echo "::set-output name=image::${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:$IMAGE_TAG"

      - name: Install Kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3

      - name: Setup Kubectl context to Amazon EKS
        id: kubectl-context
        run: aws eks update-kubeconfig --name $EKS_CLUSTER --region ${{ secrets.AWS_REGION }}

      - name: Update k8s deployment image
        id: update-image
        run: |
          kubectl set image deployment/realtor-app-deployment realtor-app=${{steps.build-image.outputs.image}}
